# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  	fileSystems."/" = {
		device = "/dev/disk/by-uuid/270b0435-6bf1-4f83-bd71-13a89dbde52d";
      		fsType = "btrfs";
		options = [ "subvol=@" ];
    	};

	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/090E-221D";
      		fsType = "vfat";
      		options = [ "fmask=0077" "dmask=0077" ];
    	};

	#swapDevices = [ { device = "/dev/disk/by-uuid/be423a69-88f8-427b-b2d0-034d8cdbe073"; } ];

	  swapDevices = [ { device = "/dev/disk/by-uuid/5d31e109-1bc7-415d-87bd-00f8affa40f5"; } ];

	  #swapDevices = [ { device = "/dev/disk/by-uuid/5d31e109-1bc7-415d-87bd-00f8affa40f5"; } ];

#/dev/disk/by-uuid/cf0e5e3b-6a0b-4199-b074-16d26dc02d98";

	hardware.enableAllFirmware = true;
	hardware.cpu.amd.updateMicrocode = true; #lib.mkDefault config.hardware.enableRedistributableFirmware;
}
/*
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  fileSystems."/" =
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/090E-221D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };


  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
*/
